### ISSUE TITLE
[EXI] potential uncovered path in switch statements might lead to bugs

### ISSUE THREAD

**Issue by HossamElwahsh** [AbdelrhmanWalaa/Moving-Car-Project#1]
All switch cases in [exi_program.c#L44](https://github.com/AbdelrhmanWalaa/Moving-Car-Project/blob/ae7c51ad524108c32b1c776d09c9e061e557bf8d/Moving%20Car/MCAL/exi/exi_program.c#L44) must contain a `default` case that returns `error` to cover wrong inputs. not adding this could lead to bugs / unknown behavior when the module is used by some other drivers, as It won't return anything in that case (wrong inputs)

**Comment by AbdelrhmanWalaa** [comment]
There is one big if statement checks the input parameters, avoiding any wrong inputs.

From: Hossam ***@***.***>
Sent: Thursday, April 13, 2023 01:44 AM
To: ***@***.***>
Cc: Abdelrhman ***@***.***>; ***@***.***>
Subject: [AbdelrhmanWalaa/Moving-Car-Project] [EXI] potential uncovered path in switch statements might lead to bugs (Issue #1)


All switch cases in exi_program.c#L44<https://github.com/AbdelrhmanWalaa/Moving-Car-Project/blob/ae7c51ad524108c32b1c776d09c9e061e557bf8d/Moving%20Car/MCAL/exi/exi_program.c#L44> must contain a default case that returns error to cover wrong inputs. not adding this could lead to bugs / unknown behavior when the module is used by some other drivers, as It won't return anything in that case (wrong inputs)

**Comment by HossamElwahsh** [comment]
@AbdelrhmanWalaa That's right, my bad thanks for clarifying 💯 , closing this issue.
